smartcontractkit/.github

actions/ci-lint-go/action.yml

We skip caching within the linting setup if we already have it enabled
for the setup-go action here.

Make golangci-lint caching dynamic

---

.github/workflows/pull-request-main.yml
.github/workflows/push-main.yml
.github/workflows/schedule-renovate.yml

Updating `actions/checkout` references in this repository's workflows.
- `v4.1.0` -> `v4.1.1`
This is an extremely minor change but had already completed it and wanted to keep this separate from the updates to the actions definitions within this repository.
---
[RE-1955](https://smartcontract-it.atlassian.net/browse/RE-1955)

[RE-1955] chore: bump actions/checkout references in workflows

---

actions/ci-lint-charts/action.yml
actions/ci-lint-go/action.yml
actions/ci-lint-misc/action.yml
actions/ci-lint-ts/action.yml
actions/ci-sonarqube/action.yml
actions/ci-test-go/action.yml
actions/ci-test-sol/action.yml
actions/ci-test-ts/action.yml
actions/cicd-build-publish-artifacts-go/action.yml
actions/cicd-build-publish-artifacts-ts/action.yml
actions/cicd-build-publish-charts/action.yml
actions/cicd-changesets/action.yml
actions/guard-from-missing-changesets/action.yml
actions/guard-tag-from-branch/action.yml
actions/setup-gap/action.yml
actions/setup-renovate/action.yml
actions/update-actions/action.yml
actions/wait-for-workflows/README.md
libs/nx-chainlink/src/generators/create-gh-action/files/composite/action.yml.template

Updating `actions/checkout` references in this repository's workflows. Updating to v4 updates the default runner to `node20`.
- `v3.6.0` -> `v4.1.1`
---
[RE-1955](https://smartcontract-it.atlassian.net/browse/RE-1955)

[RE-1955] chore: bump actions/checkout references in actions

---

actions/cicd-build-publish-artifacts-go/action.yml
actions/setup-gap/action.yml

Updating `aws-actions/amazon-ecr-login` references in this repository's workflows. Updating to v2 updates the default runner to `node20`.
- `v1.7.1` -> `v2.0.1`
---
[RE-1955](https://smartcontract-it.atlassian.net/browse/RE-1955)

chore: bump aws-actions/amazon-ecr-login from 1 to 2

---

.github/workflows/schedule-renovate.yml

Renovate bot is currently setup to run once per day. If we want to maintain a process of using renovate bot for most updates, we should be able to manually trigger it when we are hoping to:
1. Update a large number of dependencies within a day
* Don't have to wait multiple days to update all dependencies, as the max appears to be 4 per invoc. 
2. Manually trigger an update for a recently updated transitive dependency.
* Don't have to wait for renovate bot schedule to have it update a dependency.

Add ability to manually invoke renovate bot

---

.changeset/sour-needles-occur.md
actions/setup-nodejs/action.yml

Needed for [RE-2033](https://smartcontract-it.atlassian.net/browse/RE-2033), https://github.com/smartcontractkit/.github/pull/60, https://github.com/smartcontractkit/chainlink-contracts-deprecated/pull/2.
Even with a `cd` before calling this action, the `package.json` cannot be found if it's not in the package root.
Tested with:
- PR: https://github.com/smartcontractkit/chainlink-contracts-deprecated/pull/2/files
- Action: https://github.com/smartcontractkit/chainlink-contracts-deprecated/actions/runs/7093362113/job/19306593998#step:3:3

feat: sub-directory input for setup-nodejs action

---

.changeset/friendly-pans-pretend.md
actions/ci-publish-npm/README.md
actions/ci-publish-npm/action.yml
actions/ci-publish-npm/package.json
actions/ci-publish-npm/project.json
pnpm-lock.yaml

As part of [RE-2033](https://smartcontract-it.atlassian.net/browse/RE-2033) - create a reusable npm publishing action based off [smartcontractkit/ccip/.github/workflows/solidity](https://github.com/smartcontractkit/ccip/blob/7d332c917a190a5ef89e279213f72968efc4fe32/.github/workflows/solidity.yml#L162-L221).
Will be used initially in https://github.com/smartcontractkit/chainlink-contracts-deprecated/pull/2
Testing:
- https://github.com/smartcontractkit/chainlink-contracts-deprecated/actions/runs/7147133338/job/19466124711
<details>
<summary><i>Test run output</i></summary>
```
Run smartcontractkit/.github/actions/ci-publish-npm@feat/ci-publish-npm
Run echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" >> ~/.npmrc
Run pnpm publish-test --publish-branch 'feat/publishing-follow-up' …
```

feat: ci-publish-npm action

---

.github/workflows/push-main.yml

Partial roll out for the `signed-commits` action which acts as a drop-in replacement of `changesets/action`. 
This points the `cd-release` job to the branch in #80 instead of referencing the local action which is still using `changesets/action` under-the-hood.
See https://github.com/smartcontractkit/.github/pull/80 for more context.

feat: partial roll-out for cicd-changesets w/ signed commits

---

actions/signed-commits/package.json

Mark `signed-commits` as private because workflow failed.
https://github.com/smartcontractkit/.github/actions/runs/7226453502/job/19692053908

fix: flag signed-commits as private

---

.changeset/soft-radios-breathe.md
actions/cicd-changesets/action.yml

Full roll-out for `cicd-changesets` with `signed-commits`. This PR uses the new `signed-commits` action which is a drop-in replacement for the `changesets/action`, but offers signed commits and therefore "signed" tags.
#80 is another PR which has been referenced in other repos during the partial roll-out. This partial roll-out confirmed compatibility of the update. As a follow-up, those partially rolled-out repos will need to be updated to reference the official release. The tracking of updating those references will be done in that PR. 
---
https://smartcontract-it.atlassian.net/browse/RE-1901
Related to #80.

feat: cicd-changesets using signed-commits

---

.github/workflows/push-main.yml

Removing reference to the partial rollout branch - #80.
By checking out the repo and not directly referencing the `cicd-changesets` release/tag - this guarantees it will use the version at current ref.
I think this is the right way to do this as the action belongs to this repository, and if the action is updated, the workflow should use the version at the current ref rather than the last releases. Thoughts?

chore: full roll out for signed-commits (undo partial rollout)

---

.changeset/healthy-fans-behave.md
actions/signed-commits/dist/index.js
actions/signed-commits/src/git/github-git/repo-tags.test.ts
actions/signed-commits/src/git/github-git/repo-tags.ts

Found this bug with https://github.com/smartcontractkit/functions-toolkit/pull/52 ([example run](https://github.com/smartcontractkit/functions-toolkit/actions/runs/7545689293/job/20548039097)).
Cause of the error is similar to that for the remote tags issue which was solved before merging the PR in: 9a45935fe6184f2f010f2c8871b6593beb4d66d6
```
setting git user
/usr/bin/git config user.name "github-actions[bot]"
/usr/bin/git config user.email "github-actions[bot]@users.noreply.github.com"
setting GitHub credentials
No changesets found, attempting to publish any unpublished packages to npm
No user .npmrc file found, creating one
/opt/hostedtoolcache/node/18.19.0/x64/bin/npx changeset publish
🦋  info npm info @chainlink/functions-toolkit
🦋  warn @chainlink/functions-toolkit is not being …
```

fix: signed-commits crash when no local tags exist

---

.github/renovate.json

To avoid a lot of spam from renovate, we should skip patch updates for dev dependencies.

config: renovate - skip dev dependency patch updates

---

.changeset/large-walls-hear.md
actions/ci-lint-charts/action.yml
actions/ci-lint-go/action.yml
actions/ci-lint-misc/action.yml
actions/ci-lint-ts/action.yml
actions/ci-sonarqube/action.yml
actions/ci-test-go/action.yml
actions/ci-test-sol/action.yml
actions/ci-test-ts/action.yml
actions/cicd-build-publish-artifacts-go/action.yml
actions/cicd-build-publish-artifacts-ts/action.yml
actions/cicd-build-publish-charts/action.yml
actions/cicd-changesets/action.yml
actions/guard-from-missing-changesets/action.yml
actions/helm-version-bump-receiver/action.yml
actions/manifest-build/action.yml
actions/setup-gap/action.yml
actions/update-actions/action.yml
libs/nx-chainlink/src/generators/create-gh-action/files/composite/action.yml.template

Updated all actions which reference `push-gha-metrics-action` to accept a new *optional* `gc-org-id` input, and pass that to the action which has been updated for support with grafana self-hosted.
Also tried to generify references to grafana *cloud* to just grafana
- Kept inputs prefixed with `gc-` for backwards compatibility as there are many references to these shared actions with `@main`.

feat: support grafana org/tenant id input for push-gha-metrics-action v2.1.0

---

.changeset/seven-balloons-repeat.md

These are all the packages which have been updated by renovate but haven't been versioned.
As a follow-up we should figure out a way to automatically add changesets to renovate bot PRs.

chore: add changesets for renovate changes

---

.changeset/blue-schools-kneel.md
actions/ci-publish-npm/action.yml

Update the `ci-publish-npm` action to:
1. Create a github release using the `gh cli` intead of an action
2. Create the github release after the publish
3. Add the ability to link a changelog into the github release message

ci-publish-npm - feat: reorder publishing, add changelog path

---

.changeset/weak-walls-walk.md
actions/ci-lint-go/action.yml
actions/ci-test-go/action.yml
actions/cicd-build-publish-artifacts-go/action.yml
actions/cicd-build-publish-charts/action.yml
actions/cicd-changesets/action.yml
actions/setup-gap/action.yml
actions/setup-github-token/action.yml
actions/setup-nix/action.yml
actions/update-actions/action.yml

For all references of `aws-actions/configure-aws-credentials` set `mask-aws-account-id: true`.
This will avoid leaking account IDs accidentally.
---
RE-2443

chore: mask aws account id

---

.changeset/hungry-dryers-mate.md
actions/signed-commits/action.yml
actions/signed-commits/src/__snapshots__/run.test.ts.snap
actions/signed-commits/src/index.ts
actions/signed-commits/src/run.test.ts
actions/signed-commits/src/run.ts

This adds a new input to `signed-commits` action:
```
prDraft:
description:
A boolean value to indicate whether the pull request should be a draft or
not. Default to `false`
required: false
default: "false"
```

add prDraft input to changeset signed-commits action

---

.changeset/heavy-rivers-check.md
actions/cicd-changesets/action.yml

This adds two new optional inputs to `cicd-changeset` action:
```
pr-title:
description: "title of the PR"
required: false
pr-draft:
description: "whether to put the PR in draft mode or not"
required: false
default: "false"
```

add pr-draft and pr-labels to cicd-changeset action

---

.changeset/slow-brooms-grow.md
actions/cicd-changesets/action.yml

This fixes the issue where updating an existing PR does not include the draft mode option.

fix: cicd-changesets upsert pr draft mode

---

.changeset/five-eels-listen.md
actions/signed-commits/src/run.ts

Fix based on this:
https://github.com/smartcontractkit/.github/pull/278#discussion_r1556434525

fix: upsert pr with draft mode for signed-commits

---

.changeset/twelve-pants-reply.md
actions/setup-gap/action.yml

We need `v1.8` of the `aws-sigv4-proxy` which supports the `--duplicate-headers <Header>` flag ([commit](https://github.com/awslabs/aws-sigv4-proxy/commit/5770ebf7f95b58bad15546a2d1827040d61ec611)).

feat: support duplicating authorization header

---

.changeset/tiny-lions-complain.md
actions/helm-version-bump-receiver/action.yml

This updates the `helm-version-bump-receiver` action to have a check to see whether there is a diff between the two helm chart versions and fail if there is no diff.
Tested here:
https://github.com/smartcontractkit/infra-k8s/actions/runs/8709381344/job/23888911387

add check for version diff for helm-version-bump-receiver action

---

.changeset/brown-brooms-beg.md
actions/ci-publish-npm/action.yml

During  the `gh release create` for `ci-publish-npm` action, pass `--title` parameter as well. 
This creates basically no visible difference to the release. The difference can be seen when querying the API. 
When listing releases ([api](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#list-releases)) there's two fields
```
"tag_name": "<tag>",
"name": "<title>",
```
`name` here is `null` if `--title <tag>` is not passed. This created issues with the github slack announcement integration where it uses the `name` field with no fallback mechanism.
> New release published by [github-actions[bot]](https://github.com/apps/github-actions)
> [Release - undefined](https://github.com/smartcontractkit/chainlink/releases/tag/contracts-v1.1.0)

fix: ci-publish-npm add title to github release

---

.github/workflows/pull-request-main.yml

Adding the `gha-workflow-validator` introduced in #324 to this repository's workflows.

chore: add gha-workflow-validator to pull-request-main

---

.changeset/sharp-sloths-sing.md
actions/cicd-build-publish-charts/action.yml

Found this `node16` reference in the wild. Need to update this action.

chore: bump azure/setup-helm to v4.2.0

---

.changeset/clever-pots-rush.md
apps/actions-dependencies-updater/src/updater.mts

Found an issue where a repository had `uses: "actions/checkout@v3"`, this broke the text replacement which was not expecting any quotations.

fix: edge case for replacing with quoted yaml

---

.changeset/angry-panthers-leave.md
.changeset/modern-worms-hide.md
.changeset/shiny-lies-invite.md
apps/actions-dependencies-updater/README.md
apps/actions-dependencies-updater/src/caches.mts
apps/actions-dependencies-updater/src/github.mts
apps/actions-dependencies-updater/src/index.mts
apps/actions-dependencies-updater/src/updater.mts
apps/actions-dependencies-updater/src/utils.mts
apps/actions-dependencies-updater/src/workflows.mts

This introduces three new features to the `actions-dependencies-updater`
1. Partial support for `workflow_call` jobs, that is jobs which invoke a workflow rather than have steps
2. A `--skip-checks` flag to skip the recursive dependency checks
3. Debug information tracking for requests to github due to rate limits
4. Cache parsed actions to speed up processing (immutable references only)
5. A runtime cache to track which dependencies are direct, to limit unnecessary requests to github
Will test on some repos once I'm no longer rate limited.

feat: actions-updater workflow_call, and caching improvements

---

.github/workflows/pull-request-main.yml
.github/workflows/push-main.yml
apps/actions-dependencies-updater/package.json
package.json
pnpm-lock.yaml

Update rest of repo to pnpm 9 as per `.tool-versions`
- https://github.com/smartcontractkit/.github/blob/main/.tool-versions#L2

chore: update to pnpm 9

---

.changeset/honest-ladybugs-try.md
actions/setup-github-token/action.yml

Adding an optional role session name input to setup-github-token. It's an optional parameter, so it's not a breaking change.
I'm not sure if the proposed default value is the best one, but I'm still new and open to suggestions.
Ticket: https://smartcontract-it.atlassian.net/browse/RE-1943
Tested from my branch: https://github.com/smartcontractkit/releng-test/actions/runs/9353197177

RE-1943: Add optional role session name input on setup-github-token

---

.changeset/fast-drinks-reflect.md
actions/setup-github-token/action.yml

The bug is introduced by me in the PR: https://github.com/smartcontractkit/.github/pull/418
Ticket: https://smartcontract-it.atlassian.net/browse/RE-1943
Making sure that we pass truncated version that isn't longer than 64 characters. We can't override the input in any case but can set an ENV variable from value from output and use it to pass value to the next step. 
PR:  https://github.com/smartcontractkit/releng-test/pull/32
Workflow: https://github.com/smartcontractkit/releng-test/actions/runs/9355569595/job/25751900742#step:2:30

RE-1943: Fixing the optional role session name input on setup-github-token

---

.changeset/weak-lions-exist.md
actions/setup-gap/action.yml

We don't want to push metrics for jobs that use this action and already do their own metrics collection

The setup-gap action is commonly used in jobs that already have a metrics collection

---

libs/nx-chainlink/src/generators/create-gh-action/files/composite/debug/action.yml.template
libs/nx-chainlink/src/generators/create-gh-action/files/composite/default/action.yml.template

For the`create-gh-action` script templates, updated `push-gha-metrics-action` to `v3.0.1`, and is now conditional based on `metrics-job-name` being passed

chore: update create-gh-action script

---

.changeset/loud-buttons-approve.md
actions/ci-kubeconform/action.yml
actions/ci-lint-charts/action.yml
actions/ci-lint-go/action.yml
actions/ci-lint-misc/action.yml
actions/ci-lint-ts/action.yml
actions/ci-sonarqube/action.yml
actions/ci-test-go/action.yml
actions/ci-test-sol/action.yml
actions/ci-test-ts/action.yml
actions/cicd-build-publish-artifacts-go/action.yml
actions/cicd-build-publish-artifacts-ts/action.yml
actions/cicd-build-publish-charts/action.yml
actions/cicd-changesets/action.yml
actions/guard-from-missing-changesets/action.yml
actions/helm-version-bump-receiver/action.yml
actions/llm-pr-writer/action.yml
actions/manifest-build/action.yml
actions/setup-gap/action.yml
actions/setup-nix-gati/action.yml
actions/setup-nix/action.yml
actions/update-actions/action.yml
libs/nx-chainlink/src/generators/create-gh-action/files/composite/debug/action.yml.template
libs/nx-chainlink/src/generators/create-gh-action/files/composite/default/action.yml.template

* bump push-gha-metrics-action to v3.0.1
* make grafana inputs optional
* Only try and run metrics action if `metrics-job-name` was passed
* This also includes backwards compatibility for usages that do not include the `metrics-id` input (required parameter for v3), if not included it will default to the `metrics-job-name`.

chore: bump push-gha-metrics-action to v3.0.1

---

.github/workflows/pull-request-main.yml

Use `gha-workflow-validator` v0.2.0 to validate all changes to all action definitions in in the repo, not just those in the .github directory.
This is useful for this monorepo which contains many composite actions which should be validated similarly to a workflow.

ci: use gha-workflow-validator for all actions

---

.changeset/grumpy-mayflies-explain.md
actions/check-git-tag-for-monorepo/README.md
actions/check-git-tag-for-monorepo/action.yml
actions/check-git-tag-for-monorepo/package.json
actions/check-git-tag-for-monorepo/scripts/check-git-tag-for-monorepo.sh

The change is backward compatible and optionally allows using semantic version compatible tag with the `-hotfix-<increment, e.g. timestamp>` suffix.

Optionally allow hotfix suffix in the monorepo tag

---

.changeset/young-roses-impress.md
actions/ci-test-ts/action.yml
libs/nx-chainlink/src/generators/create-gh-action/generator.spec.ts

Reverting the changes to `ci-test-ts` as the steps are the same as in `ci-lint-ts` to run `nx` test targets. 
I've tested the commands on https://github.com/smartcontractkit/releng-ts-app and they both work good.

fix: update ci-test-ts to run nx test targets

---

.github/renovate.json
pnpm-lock.yaml

Started looking into this after discussions [here](https://chainlink-core.slack.com/archives/C03UV9B7M3L/p1719583508860899?thread_ts=1719571377.932819&cid=C03UV9B7M3L) 
- Renovate will group all minor and patch dependencies together by package manager name and create PRs with branch named after package manager `npm-dependencies`, `github-actions-dependencies` etc
- Major dependencies will continue to be raised separately per dependency

Group Dependencies in Renovate

---

actions/wait-for-workflows/README.md

The `wait-for-workflows` README contained improper pathing to the action.
* Also updated the `actions/checkout` ref to be a commit
* Also update the `wait-for-workflows` ref to be a placeholder example

docs: fix wait-for-workflows README

---

apps/go-mod-validator/package.json
apps/go-mod-validator/project.json
apps/go-mod-validator/test/deps.test.ts
apps/go-mod-validator/test/github.test.ts
jest.config.ts
pnpm-lock.yaml

```
❯ pnpm nx run-many -t test --no-cache
✔  nx run actions-dependencies-updater:test (806ms)
✔  nx run go-mod-validator:test (864ms)
✔  nx run gha-workflow-validator:test (920ms)
✔  nx run nx-chainlink:test (2s)
✔  nx run signed-commits:test (4s)
———————————————————————————————————————————————————————————————
>  NX   Successfully ran target test for 5 projects (4s)
With additional flags:
--cache=false
```

fix: use vitest for go-mod-validator tests

---

.changeset/brown-fans-whisper.md
actions/ci-test-go/action.yml

Adding GORACE env var set to create separate files for race traces
> [jmank88](https://github.com/jmank88) [1 hour ago](https://github.com/smartcontractkit/chainlink-feeds/pull/76#discussion_r1684412507)
Is this the line that will be run?
https://github.com/smartcontractkit/.github/blob/main/actions/ci-test-go/action.yml#L75
> Can we update that with the GORACE env var set to create separate files for race traces? Otherwise they are mixed in with test logs and can be difficult to find. In core we add this: GORACE="log_path=$PWD/race"

Adding GORACE env var set to create separate files for race traces

---

.changeset/calm-ducks-hope.md
actions/setup-crib-environment/README.md

In my previous PR the change-set file was missing. This would just build a new version of the action.

Bumping the minor version of CRIB GH action

---

.changeset/strange-birds-trade.md
actions/setup-crib-environment/action.yml

* Expose devspace namespace so it can be read by other steps in the workflow
* rename to lower case for consistency

Expose devspace namespace

---

.changeset/late-moons-fetch.md
actions/setup-crib-environment/action.yml

External repos weren't able to clone the crib repo. This fixes that.

Pass github-token via input

---

.changeset/rich-dancers-invite.md
actions/setup-crib-environment/action.yml

- Switch gap port to less likely used one
- Fix working dir, remove working dir parameter and make it dependent on the product input arg
- make nix develop to work inside crib directory
Testing:
* tested in crib repo: https://github.com/smartcontractkit/crib/actions/runs/10285734587
* and it worked in chainlink repo as well

Make setup-crib to support running from extarnal repos

---

.changeset/cold-beans-sin.md
actions/setup-gap/action.yml

Removes `checkout-repo` and `checkout-repo-fetch-depth` from the `setup-gap` action.
RE-2865

fix: remove checkout-repo for setup-gap

---

.changeset/twenty-frogs-think.md
actions/gha-workflow-validator/dist/index.js
actions/gha-workflow-validator/src/__tests__/action-reference-validation.test.ts
actions/gha-workflow-validator/src/__tests__/github.test.ts
actions/gha-workflow-validator/src/__tests__/run.test.ts
actions/gha-workflow-validator/src/__tests__/utils.test.ts

Mock core logging methods to reformat logs before they are outputted, so logs from the unit tests don't show up as actual logs from the workflow run.
RE-2854

fix: stub logging so it's not displayed as logs in ci

---

.changeset/brave-balloons-juggle.md
.changeset/shaggy-jokes-glow.md
.github/pull_request_template.md
actions/crib-deploy-environment/README.md
actions/crib-deploy-environment/action.yml
actions/crib-purge-environment/README.md
actions/crib-purge-environment/action.yml

- Add an extra step to label the Kubernetes namespace and associate it with the GitHub context.
- Improve parameter descriptions.
- Add basic documentation to the composite CRIB actions.
As a CRIB user, I’d like to be able to debug if something fails. I want to find the namespace by PR number, GitHub branch, or commit.

Adding an extra step to label the Kubernetes namespace and associate it with GitHub context

---

.changeset/modern-cycles-grow.md
actions/crib-deploy-environment/action.yml

See title.
Fixes this error:
> error: invalid label value: “branch=crib-264/crib-slack-alerts”: a valid label must be an empty string or consist of alphanumeric characters, ‘-’, ‘_’ or ‘.’, and must start and end with an alphanumeric character (e.g. ‘MyValue’,  or ‘my_value’,  or ‘12345’, regex used for validation is ‘(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?’)

Sanitize branch name for valid K8s label value

---

.changeset/big-dragons-cough.md
actions/crib-deploy-environment/action.yml

After removing the post deploy hook here: https://github.com/smartcontractkit/crib/pull/119/files#diff-1b44374eedc5da9022d1ee7a59efe99af06e54c90b30e980355438e7023c3041L106 which was necessary to fix a [bug](https://chainlink-core.slack.com/archives/C0637K4BBC2/p1724400971167039).
TTL label is no longer applied in the CI flow. This should backfill previous behavior in the CI flow

Apply TTL label from input

---

actions/crib-deploy-environment/action.yml

Once https://github.com/smartcontractkit/crib/pull/132 is merged, the CCIP UI application will be included in CRIB. This change is to make sure our smoke test covers it as well.
It's harmless to merge it before https://github.com/smartcontractkit/crib/pull/132, since it's a new env var which is atm not interpreted by CRIB.

CRIB-350: adding CCIP UI to the smoke test

---

.changeset/great-camels-tell.md

my bad, did the PR before I read the README.md instructions. This bumps the version of crib-setup-environment, which already contains the desired change.

crib-setup-deployment version bump after https://github.com/smartcontractkit/.github/pull/587

---

.changeset/lemon-experts-wonder.md
actions/setup-gap/action.yml

- Update default value to `gap-name` to `execute-api`. I believe this should almost always be `execute-api` except for certain crib use-cases?
Discovered this error when trying using `setup-gap@main` for a new workflow.
```
ERRO[0003] error proxying request                        message="{\"message\":\"Credential should be scoped to correct service: 'execute-api'. \"}" request="POST https://<redacted>.execute-api.us-west-2.amazonaws.com/primary/<endpoint>" status_code=403
```
---
https://github.com/awslabs/aws-sigv4-proxy?tab=readme-ov-file#configuration
| Flag (or short form)          | Type     | Description                                                | Default |
|-------------------------------|----------|------------------------------------------------------------|---------|
| …

fix: set gap-name default to execute-api

---

apps/go-mod-validator/test/e2e.test.ts
pnpm-lock.yaml

These tests has beed failing last few days and they are blocking many PRs in the repo.
We should figure out the fix and re-enable them once they are stable
We have removed temporarily `ci-tests` check from protected branch, to unblock PRs. After this PR we could re-enable it.
CC: @HenryNguyen5

Skip flaky tests, until they are fixed in CI

---

.changeset/swift-radios-stare.md
actions/ctf-setup-go/README.md
actions/ctf-setup-go/action.yml
actions/ctf-setup-go/package.json
actions/ctf-setup-go/project.json

This migrates ctf-setup-go from [smartcontractkit/chainlink-github-actions](https://github.com/smartcontractkit/chainlink-github-actions/tree/main/chainlink-testing-framework) repository to this repo. Once merged, I will proceed to update all workflows that utilize these actions and subsequently remove the actions from the original smartcontractkit/chainlink-github-actions repository.

Add ctf-setup-go action

---

.changeset/fluffy-meals-allow.md
actions/ctf-cleanup/README.md
actions/ctf-cleanup/action.yml
actions/ctf-cleanup/package.json
actions/ctf-cleanup/project.json

This migrates ctf-cleanup from [smartcontractkit/chainlink-github-actions](https://github.com/smartcontractkit/chainlink-github-actions/tree/main/chainlink-testing-framework) repository to this repo. Once merged, I will proceed to update all workflows that utilize these actions and subsequently remove the actions from the original smartcontractkit/chainlink-github-actions repository.

Add ctf-cleanup action

---

.changeset/proud-falcons-repair.md
actions/ctf-setup-run-tests-environment/README.md
actions/ctf-setup-run-tests-environment/action.yml
actions/ctf-setup-run-tests-environment/package.json
actions/ctf-setup-run-tests-environment/project.json

This migrates `ctf-setup-run-tests-environment` from [smartcontractkit/chainlink-github-actions](https://github.com/smartcontractkit/chainlink-github-actions/tree/main/chainlink-testing-framework) repository to this repo. Once merged, I will proceed to update all workflows that utilize these actions and subsequently remove the actions from the original smartcontractkit/chainlink-github-actions repository.

Add ctf-setup-run-tests-environment action

---

.changeset/plenty-pans-fly.md
actions/ctf-build-image/README.md
actions/ctf-build-image/action.yml
actions/ctf-build-image/package.json
actions/ctf-build-image/project.json

This migrates ctf-build-image from [smartcontractkit/chainlink-github-actions](https://github.com/smartcontractkit/chainlink-github-actions/tree/main/chainlink-testing-framework) repository to this repo. Once merged, I will proceed to update all workflows that utilize these actions and subsequently remove the actions from the original smartcontractkit/chainlink-github-actions repository.

Add ctf-build-image action

---

.changeset/wet-plants-occur.md
actions/ctf-build-tests/README.md
actions/ctf-build-tests/action.yml
actions/ctf-build-tests/package.json
actions/ctf-build-tests/project.json

This migrates ctf-build-tests from [smartcontractkit/chainlink-github-actions](https://github.com/smartcontractkit/chainlink-github-actions/tree/main/chainlink-testing-framework) repository to this repo. Once merged, I will proceed to update all workflows that utilize these actions and subsequently remove the actions from the original smartcontractkit/chainlink-github-actions repository.

Add ctf-build-tests action

---

.changeset/shiny-kids-taste.md
actions/ctf-check-mod-version/README.md
actions/ctf-check-mod-version/action.yml
actions/ctf-check-mod-version/package.json
actions/ctf-check-mod-version/project.json

This migrates ctf-check-mod-version from [smartcontractkit/chainlink-github-actions](https://github.com/smartcontractkit/chainlink-github-actions/tree/main/chainlink-testing-framework) repository to this repo. Once merged, I will proceed to update all workflows that utilize these actions and subsequently remove the actions from the original smartcontractkit/chainlink-github-actions repository.

Add ctf-check-mod-version action

---

.changeset/proud-eels-greet.md
actions/ctf-show-grafana-in-test-summary/README.md
actions/ctf-show-grafana-in-test-summary/action.yml
actions/ctf-show-grafana-in-test-summary/package.json
actions/ctf-show-grafana-in-test-summary/project.json

This migrates ctf-show-grafana-in-test-summary from [smartcontractkit/chainlink-github-actions](https://github.com/smartcontractkit/chainlink-github-actions/tree/main/chainlink-testing-framework) repository to this repo. Once merged, I will proceed to update all workflows that utilize these actions and subsequently remove the actions from the original smartcontractkit/chainlink-github-actions repository.

Add ctf-show-grafana-in-test-summary action

---

.changeset/ninety-suits-suffer.md
actions/ctf-run-tests-binary/README.md
actions/ctf-run-tests-binary/action.yml
actions/ctf-run-tests-binary/package.json
actions/ctf-run-tests-binary/project.json

This migrates ctf-run-tests-binary from [smartcontractkit/chainlink-github-actions](https://github.com/smartcontractkit/chainlink-github-actions/tree/main/chainlink-testing-framework) repository to this repo. Once merged, I will proceed to update all workflows that utilize these actions and subsequently remove the actions from the original smartcontractkit/chainlink-github-actions repository.

Add ctf-run-tests-binary action

---

.changeset/itchy-drinks-suffer.md
actions/ctf-run-tests/README.md
actions/ctf-run-tests/action.yml
actions/ctf-run-tests/mask-testsecrets/go.mod
actions/ctf-run-tests/mask-testsecrets/main.go
actions/ctf-run-tests/mask-testsecrets/main_test.go
actions/ctf-run-tests/package.json
actions/ctf-run-tests/project.json

This migrates ctf-run-tests from [smartcontractkit/chainlink-github-actions](https://github.com/smartcontractkit/chainlink-github-actions/tree/main/chainlink-testing-framework) repository to this repo. Once merged, I will proceed to update all workflows that utilize these actions and subsequently remove the actions from the original smartcontractkit/chainlink-github-actions repository.

Add ctf-run-tests action

---

libs/jira-tracing/axios.ts
libs/jira-tracing/changeset-lib.ts
libs/jira-tracing/create-jira-traceability.ts
libs/jira-tracing/enforce-jira-issue.ts
libs/jira-tracing/enforce-jira-solidity-review.test.ts
libs/jira-tracing/enforce-jira-solidity-review.ts
libs/jira-tracing/lib.test.ts
libs/jira-tracing/lib.ts
libs/jira-tracing/package.json
libs/jira-tracing/update-jira-issue.ts
pnpm-lock.yaml

Context: https://smartcontract-it.atlassian.net/browse/TT-1624
This PR adds support for appending Solidity Review issue to changeset file after either linking it to existing issue or creating a new issue from template.
Opened instead of https://github.com/smartcontractkit/chainlink/pull/14417 (already reviewed by @scheibinger), because when I started to work on this ticket this `jira-tracing` lib was still part of the `chainlink` repo. So this PR basically migrates what was done in that PR to this repo.

[TT-1624] add jira solidity review issue enforcement code

---

.changeset/calm-fishes-accept.md
libs/jira-tracing/package.json

In https://github.com/smartcontractkit/.github/pull/627 I have not bumped `libs/jira-tracing` version and thus no new tag was created, when that PR was merged. Here I do bump it.

[TT-1624] bump jira tracing version

---

.changeset/spicy-pears-yell.md
actions/gha-workflow-validator/dist/index.js
actions/gha-workflow-validator/src/__tests__/action-reference-validation.test.ts
actions/gha-workflow-validator/src/validations/action-reference-validations.ts

- Add `isWorkflowFile` to the `ActionReference` type for conditional validations for reusable workflows, and reusable actions
- Don't validate node action version for workflow file references
Found during rollout of action - https://github.com/smartcontractkit/chainlink/actions/runs/10943604627/job/30383456630?pr=14436
```
Warning: Encountered Github Request Error while getting file - smartcontractkit/.github/.github/workflows/solidity-review-artifacts.yml/action.yml@6a46410e2f2cd9efd99fd7930977931adb9153b7
```
---

fix: dont validate workflow references

---

.changeset/orange-sheep-move.md
actions/crib-deploy-environment/action.yml

This PR updates the `crib-deploy-environment` GitHub Action to enhance flexibility and align it with the recent structural changes in the CRIB repository. Instead of using the `product` name to run CRIB deployments, the action now utilizes the name of the DevSpace command configured in the CRIB repo.
* Removed `product` Input: The `product` input, which previously accepted values like `core` or `ccip`, has been replaced.
* Introduced `command` and `command-args` Inputs:
* `command`: Specifies the DevSpace command to run (default: `core`).
*` command-args`: Allows passing additional arguments to the DevSpace command (default: `--skip-build`).
Removed `devspace-profiles` Input: Profiles are now managed within the DevSpace configurations, eliminating the need for this input.
* Updated …

CRIB-304 modify crib-deploy-environment

---

.changeset/early-buses-give.md
actions/gha-workflow-validator/dist/index.js
actions/gha-workflow-validator/src/__tests__/__snapshots__/action-reference-validation.test.ts.snap
actions/gha-workflow-validator/src/__tests__/action-reference-validation.test.ts
actions/gha-workflow-validator/src/output.ts
actions/gha-workflow-validator/src/run.ts
actions/gha-workflow-validator/src/validations/action-reference-validations.ts

1. Changed logging/annotation ordering so warnings + summary are still logged before exiting
2. Updated `version-comment` action reference errors, and the logic for "trusted" actions
* If an action ref is trusted, a `version-comment` error will still appear if they used a `sha` ref
---

fix: annotations, version comment edge case

---

.changeset/shaggy-coats-joke.md
actions/gha-workflow-validator/dist/index.js
actions/gha-workflow-validator/src/__tests__/action-reference-validation.test.ts
actions/gha-workflow-validator/src/validations/action-reference-validations.ts

A bug was found internally that broke parsing of local action references when the action reference's path was in quotes. This addresses this bug.
- Fix parsing of actions when wrapped in quotes
- Added unit tests
---

fix: parse quoted action references properly

---

.changeset/afraid-rings-wonder.md
actions/ci-prettier/action.yml

RE-3058 Adding support for generating .tool-versions default file. 
In order to avoid creating the [required file](https://github.com/smartcontractkit/.github/blob/ef7717407a45c59833fe792d6d767bc21d6d1def/actions/ci-prettier/action.yml#L60) in the main repo, I think it's easier just to generate it based on the version. This change doesn't affect existing approach.

RE-3058 Adding support for generating .tool-versions default file

---

.changeset/gorgeous-months-flash.md
actions/md-confluence-sync/action.yml

Adding a lint step to the MD docs sync GHA based on prettier. 
Enforce the same style.

Adding a lint step to the MD docs sync GHA

---

.changeset/dull-pugs-wink.md
actions/setup-nix-cache/CHANGELOG.md
actions/setup-nix-cache/README.md
actions/setup-nix-cache/action.yml
actions/setup-nix-cache/package.json
actions/setup-nix-cache/project.json
actions/setup-nix-cache/scripts/upload-to-cache.sh
actions/setup-nix/README.md
actions/setup-nix/action.yml

Usage of action example: https://github.com/smartcontractkit/gauntlet-plus-plus/pull/515

Add Support For S3 caching to Nix Setup Action

---

.changeset/light-rules-share.md
actions/crib-deploy-environment/action.yml

This is required in order to test crib after https://github.com/smartcontractkit/crib/pull/227 is merged.

exposing DEVSPACE_NAMESPACE variable to the crib CLI running inside the nix shell

---

apps/go-mod-validator/test/e2e.test.ts

- Disable `go-mod-validator` `e2e` tests, it's now failing with no change. This is because it's testing dependencies are not static.

chore: disable go-mod-validator e2e tests

---

.changeset/red-balloons-decide.md
actions/llm-action-error-reporter/action.yml
actions/llm-action-error-reporter/update_pr_comment.sh

Following the patch in 0.3.1, 0.4.0 switches over to github-action scripts to update specific comment_id instead of deciding to update the last message if it's made by the script, which has low spam reduction effect in bot-busy environments.
To test the effectiveness of the script, here are 4 test cases:
- [updating it's latest comment](https://github.com/smartcontractkit/aer_tester/pull/2)
- [not updating when no failure is detected](https://github.com/smartcontractkit/aer_tester/pull/3)
- [updating it's latest comment when there's other comments made by the same bots](https://github.com/smartcontractkit/aer_tester/pull/4)
- [insert new comment when error is found for the first time](https://github.com/smartcontractkit/aer_tester/pull/5)

llm-pr-writer 0.4.0 : switch to github-script for posting github comment for flexibility

---

.changeset/popular-camels-perform.md
.changeset/sweet-tigers-live.md
actions/crib-deploy-environment/action.yml

See title. 
The labels related to the team and product will be added to the namespace and later propagated to all resources within the specific CRIB namespace.
```
❯ kg svc -n crib-ci-b73e8 -o yaml | grep team
chain.link/team: chainlink-test-team
chain.link/team: chainlink-test-team
chain.link/team: chainlink-test-team
chain.link/team: chainlink-test-team
~/git/chainlink/crib-ingress/kyverno               
❯ kgp -n crib-ci-b73e8 -o yaml | grep product
chain.link/product: awesome-product-foo-bar
chain.link/product: awesome-product-foo-bar
chain.link/product: awesome-product-foo-bar
~/git/chainlink/crib-ingress/kyverno                  
❯ kg ns crib-ci-b73e8 -o yaml
apiVersion: v1
kind: Namespace
metadata:
annotations:
creationTimestamp: "2024-11-04T13:12:35Z"
labels:
branch: …
```

Adding additional inputs for labeling resources in the composite CRIB GHA

---

.changeset/little-ducks-behave.md
actions/crib-purge-environment/action.yml

See title. 
In some cases we may want to gracefully terminate namespace. The grace period for a namespace refers to the time Kubernetes will wait for all resources (pods, services, etc.) within the namespace to be cleaned up before the namespace itself is deleted. This allows for resources within the namespace to be gracefully terminated.

Adding support for gracefully terminating CRIB Kubernetes namespace

---

.changeset/khaki-papayas-mix.md
actions/crib-deploy-environment/action.yml

Use update setup-gap action for gap v2

---

.github/renovate.json

We don't need renovate creating PRs like https://github.com/smartcontractkit/.github/pull/679 since we allow official GH actions to use semver.

Remove renovate pinning GHA to shas

---

.changeset/forty-hats-exercise.md
actions/md-confluence-sync/action.yml
actions/md-confluence-sync/mark-sync.sh

As per discussion in slack we need to remove edit-lock to unblock the deletion flow, which relies on adding `delete_pls` label
Tested here with `dry_run=true`:
https://github.com/smartcontractkit/crib/actions/runs/11794836268/job/32853275890
Tested with `dry_run=false`:
https://github.com/smartcontractkit/crib/actions/runs/11794890547/job/32853457605

feat: Prepend banner and remove lock

---

.changeset/chilled-wombats-tickle.md
actions/setup-gap/action.yml

See title. 
We would like to ensure that the proxy is up and running. I know that the docker run command should fail if the container exits with a non-zero status, but it would also be nice to verify and confirm that it's up and running.
```
Status: Downloaded newer image for envoyproxy/envoy:v1.31.0
2c3d6402e01bc3a935bad0cf38c6f8134c228e71806629a6d4e139d679a87dd4
Run # Check if the Envoy proxy is up and running on HTTPS port 
Waiting for the Envoy proxy to start... Attempt 1/10
Envoy proxy is up, and the HTTPS connection is successful.
```

Adding a check to ensure that Envoy proxy is up and running

---

.github/workflows/run-e2e-tests.yml

Setting the new input `collect_test_telemetry` to `true` will utilize the [workflow-telemetry-action](https://github.com/catchpoint/workflow-telemetry-action/tree/v2.0.0/) for E2E test runs.

Enables E2E Test Telemetry in GHA

---

actions/ctf-run-tests/action.yml
actions/ctf-setup-go/action.yml
actions/ctf-setup-run-tests-environment/action.yml

We have a repository ([chainlink-starknet](https://github.com/smartcontractkit/chainlink-starknet/tree/develop)) that uses [chainlink-testing-framework](https://github.com/smartcontractkit/chainlink-starknet/blob/develop/.github/workflows/integration-tests-smoke.yml#L187) to run it's integration tests. We recently added a dependency on [guauntlet-plus-plus](https://github.com/smartcontractkit/gauntlet-plus-plus) which is a private repo. This is causing our Github CI/CD steps to [fail](https://github.com/smartcontractkit/chainlink-starknet/actions/runs/11859007343/job/33051597179?pr=548) on the step that uses the [chainlink-testing-framework image](https://github.com/smartcontractkit/chainlink-starknet/blob/develop/.github/workflows/integration-tests-smoke.yml#L187). More specifically its …

Adding step in setup-go to use GATI Token in pulling private repos

---

.changeset/selfish-wombats-fetch.md
actions/setup-gap/action.yml
actions/setup-gap/envoy.yaml.template

- Use `LOGICAL_DNS` instead of `STRINCT_DNS` - I think this makes more sense. See: https://abhishekvrshny.medium.com/dns-aware-persistent-connections-abda9921db34
- Configure  keepalive, idle_timeout and  max_connection_duration. I'm not confident that these values are good long term, but we can tune them later. I have tested them and no issues.
Config parameters changed in this PR:
- `idle_timeout`: Specifies the duration of inactivity after which a connection will be closed to conserve resources.
- `max_connection_duration`: Defines the maximum allowable lifetime of a connection, regardless of activity, to ensure stability.
- `connection_keepalive.interval`: Sets the frequency at which keepalive pings are sent to maintain the connection.
- `connection_keepalive.timeout`: Determines how …

Improving Envoy config and add support for debugging

---

.changeset/small-chairs-care.md
actions/crib-deploy-environment/action.yml

- Adding ECR login to the crib-deploy-environment action, required for Helm. Deploying CRIB environments is not possible without this step. Previously, ECR login was only required for the aws-sigv4-proxy image, but now that it’s no longer used, an explicit login step is needed. 
- Bumping the setup-gap action version. The new version includes a fix for connection timeouts and supports passing extra inputs.
- Removed the `KUBECACHEDIR` environment variable, as it is not needed for GAP v2.
- Adding collect Envoy proxy logs step. We have the same step in `setup-gap` actions but it will collect only initial logs so we need it here as well. 
- Improvements and fixes in order to make CRIB using GAP v2 more reliable.

Adding ECR login to crib-deploy-environment action

---

.changeset/violet-melons-fix.md
actions/setup-gap/action.yml
actions/setup-gap/envoy.yaml.template

See title. 
We would like to use a custom header to avoid interfering with the default Authorization header, which would require changes on the app side. Also, sorting out the list of the ENVs.

Adding support for using a custom header for passing Github OIDC JWT Auth token

---

.changeset/eighty-rats-marry.md
actions/setup-gap/action.yml
actions/setup-gap/envoy.yaml.template
actions/setup-gap/json.lua

See title. 
In some cases, requests may run for a long time, and the JWT might need to be refreshed. In the current Envoy configuration, we fetch the token before the proxy starts, and there is no way to refresh it afterward.
https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter#httpcall
> asynchronous is a boolean flag. If async is set to true, Envoy will make the HTTP request and continue, regardless of the response success or failure. If this is set to false, or not set, Envoy will suspend executing the script until the call completes or has an error.
Note: I added `json.lua` file in order to be able to parse JSON properly since the lib isn't available and in order to avoid creating a custom Envoy image. Also, calls from LUA to external services are …

Adding support for dynamically fetching the JWT token for Kubernetes API access 

---

.changeset/long-carpets-unite.md
actions/crib-deploy-environment/action.yml

this should fix the issue related to the crib executable not being found in PATH, as well as caching dependencies
closes [CRIB-561 ](https://smartcontract-it.atlassian.net/browse/CRIB-561)

setting up go before running CRIB (ensures GOBIN is in place)

---

.changeset/clever-yaks-call.md
actions/crib-deploy-environment/action.yml

See title. 
See: https://github.com/smartcontractkit/.github/pull/727
This applies only to the local proxy for K8s API access.

Bumping the setup-gap action version to support dynamically pulling GitHub OIDC JWT token

---

.changeset/tiny-garlics-remain.md
actions/crib-deploy-environment/action.yml

required by https://github.com/smartcontractkit/crib/pull/189

added GH_TOKEN env var for crib-deploy-environment

---

.changeset/happy-ties-return.md
actions/crib-deploy-environment/action.yml

cribbit.sh is deprecated
Also, the CRIB CLI has the logic to ensure the namespace is ready (which includes waiting for the rolebinding creation), so no need to sleep before calling it anymore

CRIB-411: removing redundant call to cribbit.sh

---

.changeset/seven-pillows-admire.md
actions/crib-deploy-environment/action.yml

This is required for https://github.com/smartcontractkit/crib/pull/253 to work
Tested here: https://github.com/smartcontractkit/crib/actions/runs/12141161594

Use go version from cli/go.mod

---

.changeset/cool-games-teach.md
actions/crib-deploy-environment/action.yml

Required in order to consistently run PRs in crib where CLI changes are pushed. This is a backwards-incompatible change, please refer to the changesets file for details

signaling the nix shell to build CLI only when changes were made to it

---

.github/workflows/run-e2e-tests.yml
.github/workflows/run-integration-tests.yml

This PR:
* removes `logstream` related variables from resuable e2e workflow
* adds default ccip smoke test folders to artifact location (currently they are never uploaded)

[TT-1862] Remove logstream e2e workflow

---

.changeset/selfish-dancers-give.md
actions/setup-gap/action.yml

See title. 
We no longer use this ENV/output since we fetch the token dynamically, and it is used only for the K8s API proxy. 
https://github.com/smartcontractkit/.github/blob/main/actions/setup-gap/envoy.yaml.template#L67
For other services, it needs to be fetched from GitHub OIDC, and this needs to be implemented on the application side.
I forgot to clean that up here: https://github.com/smartcontractkit/.github/pull/727

Removing the JWT ENV variable and output parameter

---

.changeset/red-candles-rest.md
actions/crib-deploy-environment/action.yml

See title. 
Since these are required inputs makes no sense to use default empty values.

Removing default empty values for cost attribution labels

---

.changeset/big-buses-shake.md
actions/crib-deploy-environment/action.yml

v1.2.0 is the current latest stable release of crib

crib-deploy-environment now deploy crib v1.2.0 by default

---

.changeset/three-points-hunt.md
actions/setup-gap/action.yml

Update to the latest patches.  
To ensure the system is up-to-date with the latest fixes and improvements.

Upgrade local Envoy proxy image for GAP to v1.32.3

---

.changeset/sweet-pens-decide.md
actions/gha-workflow-validator/dist/index.js
actions/gha-workflow-validator/src/__tests__/action-reference-validation.test.ts
actions/gha-workflow-validator/src/validations/action-reference-validations.ts

- Fix bug for lines which contain `uses:` substring but are not action references (for example `statuses: write`)
- Add unit test
---
RE-3321

fix: gha-workflow-validator action reference validation bug

---

.changeset/healthy-queens-wave.md
actions/crib-deploy-environment/action.yml

See title. 
Use the latest version of the CRIB CLI.

Bumping the crib-repo-ref to use latest CLI version

---

.changeset/famous-beers-deliver.md
actions/crib-deploy-environment/action.yml

See title. 
Use the latest version of the CRIB CLI. A major bump is done to align with the CRIB major release

bumping crib-repo-ref version to latest CRIB release

---

.changeset/witty-glasses-invent.md
actions/crib-deploy-environment/action.yml

See title. 
Use the latest version of the `setup-gap` GHA version with dynamic local proxy, based on Envoy forward proxy.

Bumping the setup-gap GHA version

---

.changeset/little-months-care.md
actions/setup-gap/action.yml
actions/setup-gap/envoy.yaml.template

Refer to the title.
- The local proxy for GAP v2 always runs independently of the K8s API endpoint. Setting `use-k8s` to `false` results in the dynamic proxy not being configured or ready.  
- TLS should always be used.  
- Construct the K8s API hostname using the main DNS zone input, eliminating the need for two variables.

Improve the setup-gap action and ensure the local proxy always runs

---

.github/workflows/README.md
.github/workflows/run-e2e-tests.yml

See title. 
We are migrating to the latest version of `ctf-run-tests` GHA that uses GAP for accessing K8s API.

Migrating E2E Tests workflow to GAP v2

---

.changeset/tidy-queens-grow.md
actions/setup-gap/action.yml

See title 
Use the latest image that brings new features and fixes.

Upgrade Envoy image for setup-gap to v1.33.0

---

.changeset/heavy-parents-ring.md
actions/crib-deploy-environment/action.yml
actions/ctf-setup-run-tests-environment/action.yml
actions/policy-bot-config-validator/action.yml

See title. 
This version uses the latest Envoy version for the local proxy and has the change for adding a new custom header for routing: https://github.com/smartcontractkit/.github/pull/806

Use the latest version of the setup-gap action

---

.github/workflows/run-e2e-tests.yml

See title. 
Use the latest version of the GHA.

Bumping the ctf-run-tests GHA version in the e2e test workflow

---

.changeset/warm-shoes-hear.md
actions/crib-deploy-environment/action.yml

See title. 
This parameter has been removed from the `setup-gap` GH action and it's not needed anymore. We use the main DNS zone parameter to construct the hostname.

Removing k8s-api-endpoint input from crib-deploy-environment GH action

---

.changeset/slow-keys-provide.md
actions/setup-gap/action.yml

See title.
We always need the cert, even if we don't use K8s we need it for the dynamic proxy TLS listener.

Fix the CA cert generate step in the setup-gap GHA

---

.changeset/great-files-joke.md
actions/setup-gap/envoy.yaml.template

This pull request includes changes to improve the handling of the `x-repository` header in the `setup-gap` action. The updates ensure that the header is only added if it is not already present, preventing potential conflicts and improving log information.
Changes to header handling:
* [`.changeset/great-files-joke.md`](diffhunk://#diff-2050b87b16c3224620b6cc768bf6282e9d5b3d3cdc4f1654ed8734a4470bdca4R1-R5): Added a changeset entry to document the fix for `x-repository` header handling.
* [`actions/setup-gap/envoy.yaml.template`](diffhunk://#diff-79a9c5a425c3bc6f7414be4ef96f2a0724c806e4673c295ed564d0fdcdb99341R149-R153): Updated the Lua filter to check for the presence of the `x-repository` header before adding it. If the header is already present, a log message is generated instead. …

Fixing the x-repository header handling to avoid breaking the Lua filter

---

.changeset/make-role-optional.md
actions/setup-gap/action.yml

We only need to run the `Assume role` action when we want to access a k8s API server through the local envoy proxy. For other workflows, we should be able to skip the role assumption (and the requirement to pass a role ARN as an argument).
This PR makes the `setup-gap` action skip the `Assume role` step unless an explicit `use-k8s: true` argument is passed to it.

Remove role assumption requirement for non-k8s apiserver needs

---

.changeset/wildcard-sans.md
actions/setup-gap/action.yml

By adding all subdomains of the selected dns zone as cert SANs, clients that can't be configured with custom host headers or insecure connections can still utilize the proxy.
If you set, e.g. `127.0.0.1 my-service.my-dns-zone` in the GHA runner's `/etc/hosts` file, any client can then directly connect to e.g. `https://my-service.my-dns-zone` with full functionality.

Add all subdomains of the selected dns zone as cert SANs

---

.changeset/smooth-weeks-add.md
actions/setup-gap/envoy.yaml.template

Change the LUA script to enforce the value of the JWT token if the request is going through the local proxy.
For example, if there is already a header with a JWT token passed by the client, the LUA filter should delete it and append its own value. This is needed to:
- Ensure the LUA script doesn't crash when attempting to add a header that already exists (logic to handle it properly).
- Ensure the TTL of the JWT hasn't expired (e.g., the local client fetched it but doesn't refresh it, etc.).

Ensure the local proxy always sets the JWT header even if it's provided by the client

---

.changeset/loud-ligers-exercise.md
actions/crib-deploy-environment/action.yml

See title. 
Use the latest version with some fixes.

Bumping the setup-gap GHA version in crib-deploy-environment GHA

---

actions/setup-golang/action.yml

This pull request includes a small change to the `actions/setup-golang/action.yml` file. The change sets a default option for the `tar` command to avoid overwriting existing files when extracting files from a cache archive.
* [`actions/setup-golang/action.yml`](diffhunk://#diff-4bbc52cfa3a89bc7512f94ffb0868dfb8a88af866ff42b2483f4da7e90b3b56eR28-R33): Added a step to set `TAR_OPTIONS=--skip-old-files` in the environment to prevent overwriting existing files during extraction.
If some go dependencies already exist in the runner, when we try to extract the cache `tar` will return errors for all files that currently exist in the runner and cannot override with the ones from the cache. This can result in a lot of bloat in the GHA logs from errors that we cannot do nothing about. 
Although …

RE-3420: Remove go-setup caching errors

---

.changeset/fresh-fireants-bow.md
actions/check-if-verified/README.md
actions/check-if-verified/action.yml
actions/check-if-verified/package.json
actions/check-if-verified/project.json
actions/check-if-verified/test-check-if-verified.yml

Add `check-if-verified` action that uses the GH API to check a commit/tags signature.
With assert false: https://github.com/smartcontractkit/.github/actions/runs/12938082445/job/36087444617?pr=834
With assert true: https://github.com/smartcontractkit/.github/actions/runs/12938117106/job/36087550825?pr=834 (fails)
---
RE-3430

feat: check-if-verified action

---

.github/workflows/run-e2e-tests.yml

Why?
To be able to pass a GATI-generated GH token to tests.

[TT-1847] Optional GATI token fetching step in reusable workflow

---

.github/workflows/run-integration-tests.yml

See title. 
Use the latest version of the action that uses GAP v2.
See: https://github.com/smartcontractkit/chainlink/actions/runs/12989483457/job/36226317155?pr=16075

Migrating integration tests to the latest version of ctf-run-tests GHA

---

.changeset/healthy-shrimps-punch.md
actions/setup-golang/action.yml

This pull request includes a change to the `actions/setup-golang/action.yml` file to implement a fix in order to install the toolchain version if it exists as was introduced by this commit https://github.com/smartcontractkit/chainlink/commit/a744ed66541a3bd9b5edb2977ce5e03fa55e6356

RE-3420: Select the correct go-version

---

.changeset/smart-rules-hunt.md
actions/setup-gap/action.yml

See title. 
The majority of workflows use 443 as the default. This doesn't conflict with anything because traffic has to be explicitly routed through it.

Set the default port for the dynamic proxy to 443

---

.github/workflows/pull-request-main.yml
.github/workflows/push-main.yml
.github/workflows/run-e2e-tests.yml
.github/workflows/run-integration-tests.yml
.github/workflows/schedule-renovate.yml
.github/workflows/solidity-review-artifacts.yml

- Fix potential injection vulnerabilities found with [zizmor](https://github.com/woodruffw/zizmor)
- Add `persist-credentials: false` to any usages of `actions/checkout`
---
RE-3380

fix: potential CI injections

---

.changeset/fuzzy-wasps-hunt.md
actions/beholder-pulumi-deploy-schema/README.md
actions/beholder-pulumi-deploy-schema/action.yml
actions/beholder-pulumi-deploy-schema/package.json
actions/beholder-pulumi-deploy-schema/project.json

See [ticket](https://smartcontract-it.atlassian.net/browse/INFOPLAT-1427) for details.

[INFOPLAT-1427] Action to deploy Protobuf/AVRO schemas to Confluent Schema Registry

---

.changeset/funny-penguins-hope.md
actions/ctf-setup-run-tests-environment/action.yml

See title. 
Use the latest version that introduces a local proxy for websockets.

Bumping the setup-gap version in ctf-setup-run-tests-environment GHA

---

.changeset/fluffy-fishes-end.md
actions/ctf-setup-go/action.yml

This changes are meant to fix the wall of errors related to cache restoration we see every time we run smoke,integration tests.
1. We add the `Get Go Version` and the `Export Go version` steps in order to fix the main cause of the issue. See more here https://smartcontract-it.atlassian.net/browse/TT-1987 
2. We remove the `go-version-file` param from the `Setup Go` step, because we can have only one of `go-version-file` and `go-version`. See more here https://chainlink-core.slack.com/archives/C049X3353K2/p1738771824123779?thread_ts=1738764531.723059&cid=C049X3353K2
3. We add the `Setup tar default options` in order to remove the errors which are caused by previous runs of the cache. See more here https://chainlink-core.slack.com/archives/C038Q8K1HTR/p1738775301296369?thread_ts=1738773161.7 …

TT-1987 ctf-setup-go

---

.changeset/metal-walls-warn.md
actions/setup-gap/github_oidc.lua.gotmpl

There is a bug in the script that matched the hostname and port, which caused it to fail when the port is not provided. I have added escaping logic to prevent breaking the Lua script. This ensures that the JWT header is correctly added regardless of whether the port is specified.
Make sure proxy adds headers in case the port isn't specified in the request URL.

Properly handle the JWT header addition

---

.github/workflows/run-e2e-tests.yml

We are passing the chainlink version to test as `inputs.chainlink_version`, but whenever we checkout the calling repository (which is almost always `chainlink` or `chainlink-like`) then we checkout the latest commit from the default branch (in `chainlink` case that's `develop`). 
That might lead to weird issues, when the test is expecting that application behaves in one way (characteristic for latest commit in the default branch), but it doesn't because the image used in the test is based on `inputs.chainlink_version`.
Therefore, I think we should should be checking out repository version that corresponds to the version of application under test.

[TT-1991] checkout repository in the same version as the chainlink_version

---

.changeset/itchy-owls-scream.md
actions/ci-test-go/action.yml

Use newer version of `setup-golang` as the older version depends on a deprecated version of `actions/cache`.
---
RE-3330

chore: upgrade ci-test-go version of setup-golang

---

.changeset/perfect-panthers-hide.md
actions/ci-prettier/action.yml

Use newer version of `setup-nodejs` as the older version depends on a deprecated version of `actions/cache`.
---
RE-3330

chore: upgrade setup-nodejs version of ci-prettier

---

.changeset/mighty-tigers-develop.md
actions/crib-deploy-environment/action.yml

A few errors such as `namespace already exists` have been observed recently, this is an attempt to mitigate this issue without incurring in increasing DNS names too much.

increase ns name uniqueness for crib in CI

---

.changeset/flat-baboons-nail.md
actions/ctf-setup-run-tests-environment/action.yml

See title. 
Not all tests need GAP and access to internal services. Also, we need a flag to disable GAP, as this action is being used for different tests and environments.

Improving GAP GHA configuration in the ctf-setup-run-tests-environment GHA

---

.changeset/shaggy-eels-type.md
actions/ctf-run-tests/action.yml

We are making a change to filter only Envoy logs by image name and limit the output to the last 1,000 lines.
The existing approach collects logs from all containers, which can overwhelm the system and completely crash the GitHub UI in case of failures.

Improving GAP local proxy log handling

---

.changeset/strong-forks-collect.md
actions/setup-gap/action.yml
actions/setup-gap/envoy.yaml.gotmpl
actions/setup-gap/github_oidc.lua.gotmpl

This pull request includes several changes to enable using multiple local envoy proxies on the same workflow for the CLD repo. The most important changes include updating environment variable usage, modifying the Envoy configuration, and adding a new Lua function to ensure the correct port is used in the host header.
* [`actions/setup-gap/action.yml`](diffhunk://#diff-05506e3c2ffb5cb85e06ba106d4539bf50fe47316b49d832b8833a794efa8fceR270): Updated the `GAP_NAME` environment variable and replaced hardcoded `"gap"` with `${GAP_NAME}` in Docker run commands to dynamically set the container name. [[1]](diffhunk://#diff-05506e3c2ffb5cb85e06ba106d4539bf50fe47316b49d832b8833a794efa8fceR270) [[2]](diffhunk://#diff-05506e3c2ffb5cb85e06ba106d4539bf50fe47316b49d832b8833a794efa8fceL316-R317) …

RE-3425: Use dynamic name for the envoy container name

---

.github/workflows/run-e2e-tests.yml
.github/workflows/run-integration-tests.yml

Use a version of `ctf-run-tests` action that makes GAP optional, since it's not needed by Docker tests. And if enabled it results in printing of all Docker container logs to the console when test fails, which crashes the UI.

Reusable workflow no proxy

---

.changeset/rude-baboons-teach.md
.github/workflows/reusable-docker-build-publish.yml
actions/build-push-docker/action.yml

Otherwise each build will stomp on the other's cache.

Add docker cache scope using runner arch as a suffix for cache isolation

---

.changeset/cold-ladybugs-talk.md
.github/workflows/push-main.yml
actions/cicd-changesets/action.yml

- Updating `cicd-changesets` to use `signed-commits` `v1.4.0`. These are changes from #919.
---
RE-3546

chore: bump signed-commits to 1.4.0

---

.changeset/chilly-pianos-juggle.md
actions/setup-golang/action.yml

Use the new forked `branch-names` action in `.github`.

fix: setup-go use new branch-names

---

.changeset/curly-spoons-fix.md
actions/ci-test-go/action.yml

- Update setup-golang to  `0.3.2`.

chore: update usages of setup-golang

---

.github/workflows/run-e2e-tests.yml
actions/ctf-run-tests/action.yml

PR in core: https://github.com/smartcontractkit/chainlink/pull/16866

DX-198 Bump Flakeguard to send codeowners, test path and failed test log url to splunk in e2e tests workflow

---

.changeset/tidy-kiwis-wonder.md
actions/ctf-setup-run-tests-environment/action.yml

Part 2 of this PR: https://github.com/smartcontractkit/.github/pull/720
Adding the new G++ setup to the set up test frameworks action

Adding private ECR pull for g++ on ctf run tests setup

---

.changeset/clean-buses-mix.md
actions/signed-commits/action.yml
actions/signed-commits/dist/index.js
actions/signed-commits/src/git/github-git/repo-tags.test.ts
actions/signed-commits/src/git/github-git/repo-tags.ts
actions/signed-commits/src/index.ts

- Add support for a `/v` tag separator.
- Add tests for `/v` tags
- Fix minor bug in `parseTagName`
--
RE-3546

feat: signed-commits support /v tag separator

---

.changeset/tricky-walls-brake.md
.github/workflows/push-main.yml
actions/cicd-changesets/action.yml

- `cicd-changesets`: bump signed-commits action to 1.5.0
- `push-main` workflow: Create major version tags: true
---
RE-3546

chore: bump signed-commits to 1.5.0

---

.changeset/unlucky-chefs-talk.md

- Add a changeset to perform a major version release for our actions which are actually used.

chore: major version release for many actions

---

.changeset/purple-lions-impress.md
actions/flakeguard-ai-analysis/action.yml
actions/flakeguard-ai-analysis/main.py

ensures that we are using the `/github/workspace` directory for file lookup.
forwards the file name correctly from the workflow supplied input.

Flakeguard AI environment variable adjustment and file path fix

---

.changeset/slimy-foxes-rule.md
actions/flakeguard-ai-analysis/.gitignore
actions/flakeguard-ai-analysis/main.py
actions/flakeguard-ai-analysis/src/utils.py

successful run with this update:
https://github.com/smartcontractkit/chainlink/actions/runs/14091172597/job/39469043542
added a `FILE_PATH` value that we can override in case we do end up changing the runner in the future at some point.
when an artifact is downloaded via `actions/download-artifact@v4` it actually is a folder with the file inside of it. handling this correctly in python now. add `REPORT_FILE_NAME` in case it changes in the future.
also added a bunch of logging.

add more logging, read the file within the artifact folder

---

.changeset/warm-bikes-shave.md
actions/setup-gap/action.yml
actions/setup-gap/envoy.yaml.gotmpl

#997 broke the setup-gap preliminary health check for the K8s listener.
Switching back to something that only cares if a connection was successful rather than relying on status codes.
https://github.com/smartcontractkit/releng-test/actions/runs/14503557560/job/40689038832?pr=84
I tried adding another virtual host in for the K8s listener, but it didn't work. So going back to connection successful. The existing virtual hosts for local host requests on the dynamic and websocket proxy will remain so they don't route to envoy itself.
---
DX-541

fix: envoy proxy health check

---

actions/setup-gap/README.md

I added a testing workflow to `releng-test` which allows you to specify a branch from this repository, and run tests against the setup-gap action.
- Documentation for testing
https://github.com/smartcontractkit/releng-test/actions/runs/14525524698
---
DX-541 / https://github.com/smartcontractkit/releng-test/pull/85

docs: setup-gap testing instructions

---

.changeset/smooth-plants-train.md
actions/setup-postgres/action.yml
actions/setup-postgres/docker-compose.yml

- add `image-tag` input to `setup-postgres` action, allowing to override the previously hardcoded image.
---
RE-3523

feat: setup-postgres image-tag input

---

.changeset/shaggy-wolves-unite.md
actions/setup-gap/action.yml
actions/setup-gap/authz/main.go
actions/setup-gap/docker-compose.yml
actions/setup-gap/envoy.yaml.gotmpl
actions/setup-gap/scripts/debug-docker-compose.sh
actions/setup-gap/scripts/debug-render-template.sh

- fix: (action) add --project parameter for docker compose commands
- 	this should allow for multiple GAPs to be `up`'d
- fix: (envoy config) websocket service routing with explicit port
- this constrains the domain from any suffix, to a specific port suffix only
- fix: (authz + envoy config) host header port rewrites
- Now properly rewrites the host header to ensure a 443 port, which is what the upstream LBs are listening on. This only affected GAPs with non-standard ports
- fix: (authz) logging level environment variable name
- Fixes enabling debug logs for the authz service 
- feat: (authz) better header debug logging
- more and better logging for  	
- Test for `setup-gap/4.2.1`: https://github.com/smartcontractkit/releng-test/actions/runs/14542299406/job/40802438956
- Test for this …

fix: allow multiple instances of GAP

---

.changeset/purple-spiders-fly.md
actions/setup-gap/authz/main.go
actions/setup-gap/envoy.yaml.gotmpl

- Add missing `host` header entry for K8s and websockets
- Remove unnecessary `:authority` header for upstream headers
- Expand domains array for readability
- Update some authz logging
https://github.com/smartcontractkit/releng-test/actions/runs/14605886563
---
DX-541

fix: (setup-gap) missing host headers

---

actions/ctf-run-tests/action.yml

This pull request updates the `action.yml` file for the `ctf-run-tests` GitHub Action by introducing new input parameters and updating a referenced action version. These changes enhance configurability and ensure compatibility with the latest dependencies.
* Added `install_plugins_public` input to optionally install public LOOP plugins. It defaults to `"false"`.
* Added `aptos_cli_version` input to specify an Aptos CLI version for installation (e.g., `7.2.0` or `latest`). It defaults to an empty string.
* Updated the `ctf-setup-run-tests-environment` action version to a specific commit hash (`0e45310c4e5f3f270599b82e9c608ebc4a7dd330`) for improved stability.
* Incorporated the new inputs `install_plugins_public` and `aptos_cli_version` into the `runs` section to pass them to the setup …

Add aptos support e2e to ctf run test action

---

.changeset/empty-needles-tap.md
actions/get-pr-labels/README.md
actions/get-pr-labels/action.yml

Dont error for non PR or MQ events.
https://github.com/smartcontractkit/chainlink/actions/runs/15286494615/job/42997746992
https://github.com/smartcontractkit/releng-test/actions/runs/15286692666?pr=96

fix: get-pr-labels incompatible events

---

.changeset/clever-mails-hear.md
actions/ctf-setup-run-tests-environment/action.yml

- Add the `setup_db` parameter to the `ctf-setup-run-tests-environment` action, add steps to setup the DB when enabled.
- Use newer command to setup db that doesnt have to build the whole cl binary
`run-in-memory-tests` job (from `run-e2e-test` reusable workflow) is setting up the DB at the job level - https://github.com/smartcontractkit/.github/blob/4962346cc5ffc9f3840f48639e7b5fa179bcc2cc/.github/workflows/run-e2e-tests.yml#L1255-L1294
This creates issues because in `ctf-setup-run-tests-environment` action we are setting up go and properly restoring from the mod/build cache. This should significantly improve the time it takes to build the binary and set up the db
This also uses the `setup-postgres` reusable action now, which has `tmpfs` option which should improve database speeds.
See: …

feat: optionally setup db for ctf env

---

.changeset/yellow-files-buy.md
actions/signed-commits/dist/index.js
actions/signed-commits/src/git/github-git/repo-tags.test.ts
actions/signed-commits/src/git/github-git/repo-tags.ts

- Fixes tag rewrites when packages use namespaced prefixes like `@chainlink` (like `@chainlink/contracts@0.0.1`)
- Old behaviour would rewrite this to `/vchainlink/contracts/v0.0.1` but it should only replace the last `@`

Fix to work with scoped name packages

---

.changeset/clever-mails-hear.md
.github/workflows/run-e2e-tests.yml

- Don't setup the DB at the job level for `in-memory-tests` job
-  See related PRs: #1060, #1061 
- Don't cache `go` for `load-test-configurations` job
- This routinely takes a very long time, not sure if it's necessary for such a simple tool like ci-tool.
- Example: 5min setup-go step, and 5min post setup-go step - https://github.com/smartcontractkit/chainlink/actions/runs/15334488256/job/43148823751?pr=17943#step:3:31 
- Don't install jq as it comes automatically installed on runners
See https://github.com/smartcontractkit/chainlink/pull/17943
---
DX-931 + DX-934

feat: run-e2e-tests optionally setup db

---

.changeset/gentle-dingos-hug.md
actions/build-push-docker/action.yml

- Remove `docker-build-cache-disabled` input parameter
- Add `docker-restore-cache` and `docker-save-cache` input parameters
- These control whether to use the cache when building, and to save the cache when it's over
- Add `ignore-error=true` to the cache-to input, as errors in writing to the cache shouldn't fail the workflow.
With the single parameter, we were disabling the usage of the cache when building, but still populating the cache afterwards. For example ([run](https://github.com/smartcontractkit/chainlink/actions/runs/15401647680/job/43335457729#step:6:1659)):
```
#44 exporting to GitHub Actions Cache
#44 preparing build cache for export
#44 writing layer sha256:0c92300288a921d2452af3f7c67206c69c6572c4cb51903f3230c3a5792cfc80
#44 writing layer …
```

feat: build-push-docker cache improvements

---

.github/workflows/reusable-docker-build-publish.yml

- Adds two input parameters: `docker-cache-behaviour` and `github-trunk-branch` to control the caching behaviour. 
- Replaces the `docker-build-cache-disabled` input parameter (deleted)
https://github.com/smartcontractkit/chainlink/actions/runs/15404750247?pr=17978
#1076

chore: bump build-push-docker

---

.changeset/popular-crews-beam.md
actions/guard-tag-from-branch/scripts/tag-branch-check.sh

This was failing from CI here: https://github.com/smartcontractkit/chainlink/actions/runs/15477407422/job/43576605910#step:7:94 but working locally.
CI returns `(HEAD` for the $SOURCE_BRANCHES.

Fix filtering for branches from tag commit

---

.github/CODEOWNERS

The joint ownership added in #1104 did not help. Removing tooling completely for the time being until `devex` team is added to repo.

fix: ctf codeowners

---

.changeset/cyan-clocks-care.md
actions/do-not-merge/README.md
actions/do-not-merge/action.yml
actions/do-not-merge/package.json
actions/do-not-merge/project.json
actions/do-not-merge/scripts/do-not-merge-block.js

To prevent merging with certain labels. Will creating a failing check if a PR is opened with a specified label or if a specified label is later added.

Create do-not-merge composite action

---

.changeset/fuzzy-mugs-peel.md
actions/ctf-build-image/scripts/go-get-overrides.sh
actions/ctf-build-image/scripts/test-go-get-overrides.sh

- Fixed mismatch between `OVERRIDES` env var and `GO_OVERRIDES` env var.
- Fixed lined validation
Related to https://github.com/smartcontractkit/chainlink-solana/pull/1283

fix: ctf-build-image go dep overrides

---

.github/workflows/run-e2e-tests.yml

- Remove `test-` prefix from expected image name
- Allow for configurable ECR name
https://github.com/smartcontractkit/chainlink/pull/18536
- https://github.com/smartcontractkit/chainlink/actions/runs/16149840932?pr=18536
To reduce the number of images published to SDLC /chainlink ECR, we need to add support for integration tests to use a different ECR.
---
DX-1339

fix: remove test- prefix, allow for configurable ECR name

---

actions/apidiff-go/README.md
actions/apidiff-go/action.yml
actions/apidiff-go/dist/index.js
actions/apidiff-go/scripts/test.sh
actions/apidiff-go/src/__tests__/apidiff.test.ts
actions/apidiff-go/src/__tests__/git-worktree.test.ts
actions/apidiff-go/src/__tests__/go/multi-module-changed/go.mod
actions/apidiff-go/src/__tests__/go/multi-module-changed/main.go
actions/apidiff-go/src/__tests__/go/multi-module-changed/submodule1/go.mod
actions/apidiff-go/src/__tests__/go/multi-module-changed/submodule1/util.go
actions/apidiff-go/src/__tests__/go/multi-module-changed/submodule2/go.mod
actions/apidiff-go/src/__tests__/go/multi-module-changed/submodule2/helper.go
actions/apidiff-go/src/__tests__/go/multi-module/go.mod
actions/apidiff-go/src/__tests__/go/multi-module/main.go
actions/apidiff-go/src/__tests__/go/multi-module/submodule1/go.mod
actions/apidiff-go/src/__tests__/go/multi-module/submodule1/util.go
actions/apidiff-go/src/__tests__/go/multi-module/submodule2/go.mod
actions/apidiff-go/src/__tests__/go/multi-module/submodule2/helper.go
actions/apidiff-go/src/apidiff.ts
actions/apidiff-go/src/git-worktree.ts
actions/apidiff-go/src/run-inputs.ts
actions/apidiff-go/src/run.ts
actions/apidiff-go/src/string-processor.ts

- Some logging changes (groups)
- Change input `go-mod-path` to `go-mod-paths`, now supporting CSV paths to go mods
- Output formatting for multiple go.mods - example: https://github.com/smartcontractkit/chainlink-common/pull/1454#issuecomment-3166037330
- Tests for multi module setups
---
DX-1559

feat: apidiff-go multiple go mods

---

.github/workflows/reusable-docker-build-publish.yml

See title. 
I know it’s not great, but building some images like aptos-node takes more than 30 minutes, unfortunately.

feat: add configurable timeout input to reusable docker build workflow

---

.changeset/three-beers-clap.md
actions/codeowners-review-analysis/action.yml
actions/codeowners-review-analysis/dist/index.js
actions/codeowners-review-analysis/scripts/test.sh
actions/codeowners-review-analysis/src/github-gql.ts
actions/codeowners-review-analysis/src/run-inputs.ts
actions/codeowners-review-analysis/src/run.ts

CodeOwners Review Analysis (cora) support `pull_request_review` events.
We need this and they should contain the same context as `pull_request_events`, as per: https://docs.github.com/en/webhooks/webhook-events-and-payloads#pull_request_review
Tested with the test.sh shell script and here: https://github.com/smartcontractkit/releng-test/pull/138
---
DX-1787

feat: cora pull request review event

---

.changeset/stupid-elephants-work.md
actions/codeowners-review-analysis/README.md
actions/codeowners-review-analysis/dist/index.js
actions/codeowners-review-analysis/scripts/payload.json
actions/codeowners-review-analysis/src/__tests__/review-status.test.ts
actions/codeowners-review-analysis/src/review-status.ts
actions/codeowners-review-analysis/src/run.ts
actions/codeowners-review-analysis/src/strings.ts

- Fixes how the overall state is calculated for a PR which is different than how the overall state is calculated for a codeowners entry
- Add unit tests to enforce/check this behaviour
- Always include summary url if available
- A single codeowners entry is technically satisfied if any one of the codeowners have approved
- A full PR is technically only satisfied if every codeowners entry is satisfied, that is, every entry has at least one approval
---
DX-1787

fix: cora pr comment

---

.changeset/plenty-roses-knock.md
actions/ctf-run-tests/action.yml

This adds an optional input to install the Sui CLI at a specified version to the `ctf-run-tests` action.
Bumps `ctf-setup-run-tests-environment` to 0.8.0 to include [dependent changes](https://github.com/smartcontractkit/.github/pull/1257).

Add Sui CLI to ctf-run-tests

---

.changeset/two-bananas-allow.md
actions/apidiff-go/action.yml
actions/apidiff-go/dist/index.js
actions/apidiff-go/package.json
actions/apidiff-go/scripts/payload.json
actions/apidiff-go/scripts/test.sh
actions/apidiff-go/src/apidiff.ts
actions/apidiff-go/src/render-diff.ts
actions/apidiff-go/src/run-inputs.ts
actions/apidiff-go/src/run.ts
actions/apidiff-go/src/string-processor.ts
pnpm-lock.yaml

* Adds `post-comment` input to toggle whether to post a comment. This is mostly a local run debug parameter
* Refactor output formatting with better diff displaying support
* Most of this logic is contained in `render-diff.ts`
* Moves apidiff output parsing to `apidiff.ts` was previously in `string-processing.ts`
I've tested locally against a fee PRs
---
DX-1961

fix: apidiff-go output formatting

---

.github/workflows/run-e2e-tests.yml

* Remove input `test_log_upload_on_failure`, it was default to `true` and it was only ever passed as `true`
* https://github.com/search?q=org%3Asmartcontractkit+%22test_log_upload_on_failure%22&type=code
* Remove input `test_log_upload_retention_days` it was default to `5` and was `7` in some places, who cares?
* https://github.com/search?q=org%3Asmartcontractkit+%22test_log_upload_retention_days%22&type=code
* Remove input `upload_cl_node_coverage_artifact_prefix`, once again, who cares?
* https://github.com/search?q=org%3Asmartcontractkit%20%22upload_cl_node_coverage_artifact_prefix%22&type=code
* Remove input `extraArgs`, AFAICT this isn't used by anything recent. And was mostly used for flakeguard.
* https://github.com/search?q=org%3Asmartcontractkit+%22extraArgs%22+path%3A.github%2Fwo …

chore: cleanup run-e2e-tests.yml
