actions/ci-test-ts/action.yml
actions/cicd-build-publish-artifacts-ts/action.yml

- add qemu support
- configurable path for release assets (default=`bin/*`)
- add `check-only-affected` for ts actions

feat: update ts actions

---

.changeset/tidy-days-greet.md
actions/ci-lint-go/action.yml
actions/ci-sonarqube/action.yml
actions/ci-test-go/action.yml

Tested here:
https://github.com/smartcontractkit/chainlink-functions/actions/runs/7302420643/job/19901438281

add include-lint input to ci-sonarqube action

---

.github/workflows/pull-request-main.yml
.github/workflows/push-main.yml

Updating to use Grafana internal credentials.
---
RE-2240

chore: use grafana internal credentials

---

.changeset/thirty-birds-switch.md
actions/llm-pr-writer/README.md
actions/llm-pr-writer/action.yml
actions/llm-pr-writer/package.json
actions/llm-pr-writer/project.json

This adds a new action: `llm-pr-writer`.

add llm-pr-writer action

---

.changeset/dull-fireants-breathe.md
actions/llm-pr-writer/README.md
actions/llm-pr-writer/action.yml
actions/llm-pr-writer/pr-writer-prompt.md

These changes introduce new features and improvements to the `llm-pr-writer` action, such as support for chat commands, excluding specific paths from analysis, and appending files to PR descriptions. Additionally, they enhance error logging, making it easier for developers to troubleshoot issues. The modifications aim to streamline the PR description generation process, providing more flexibility and utility.
- **actions/llm-pr-writer/README.md**
- Expanded the README to include a more detailed description of the action, including prerequisites, usage, scenarios, and tips.
- Included information on new features such as excluding paths and appending files to PR messages.
- **actions/llm-pr-writer/action.yml**
- Updated input descriptions, emphasizing the new default model and additional …

additional features and improved error logging for llm-pr-writer 0.2.0

---

.changeset/yellow-sheep-judge.md
actions/llm-pr-writer/action.yml
actions/llm-pr-writer/pr-writer-prompt.md

Expanding the scope of github diff output to scope level to address misinterpretations occurred in PR with minimal modifications

diff scope expansion for additional context in llm-pr-writer 0.3.0

---

.changeset/slow-brooms-grow.md
actions/cicd-changesets/action.yml

Reverts smartcontractkit/.github#278

Revert "fix: cicd-changesets upsert pr draft mode"

---

.changeset/empty-kids-explain.md
actions/cicd-changesets/action.yml

- **bump signed-commits to 1.2.1 for cicd-changeset action**
- **update signed-commits 1.2.2**

fix: bump signed-commits to 1.2.2

---

.changeset/big-crabs-wave.md
.changeset/big-pandas-refuse.md
actions/ci-kubeconform/README.md
actions/ci-kubeconform/action.yml
actions/ci-kubeconform/package.json
actions/ci-kubeconform/project.json
actions/ci-lint-charts/action.yml

This adds a new action `ci-kubeconform`.
Tested here:
https://github.com/smartcontractkit/chainlink/actions/runs/8740607631?pr=12865

add ci-kubeconform action

---

.changeset/cool-houses-grin.md
apps/update-action-versions/action.yml
apps/update-action-versions/out/index.js

- Updated `action.yml` to `using: node20`
- Rebuilt dist using node20, and updated deps from renovate bot bumps
- Added changeset
Here: https://github.com/smartcontractkit/releng-ts-app/actions/runs/8855067652

chore: node20 for update-action-versions

---

.changeset/lucky-wolves-visit.md
.gitignore
apps/actions-dependencies-updater/README.md
apps/actions-dependencies-updater/package.json
apps/actions-dependencies-updater/project.json
apps/actions-dependencies-updater/src/caches.mts
apps/actions-dependencies-updater/src/generated/types/README.md
apps/actions-dependencies-updater/src/generated/types/github-action.mts
apps/actions-dependencies-updater/src/generated/types/github-workflow.mts
apps/actions-dependencies-updater/src/generated/types/index.mts
apps/actions-dependencies-updater/src/git-cli.mts
apps/actions-dependencies-updater/src/github.mts
apps/actions-dependencies-updater/src/index.mts
apps/actions-dependencies-updater/src/logger.mts
apps/actions-dependencies-updater/src/updater.mts
apps/actions-dependencies-updater/src/utils.mts
apps/actions-dependencies-updater/src/workflows.mts
apps/actions-dependencies-updater/tsconfig.json
pnpm-lock.yaml

Introducing a tool to check repositories for node12/node16 actions dependencies, and a method for updating them.

feat: github-actions-updater

---

.changeset/swift-terms-count.md
apps/actions-dependencies-updater/src/caches.mts
apps/actions-dependencies-updater/src/index.mts
apps/actions-dependencies-updater/src/updater.mts
apps/actions-dependencies-updater/src/workflows.mts

1. Clean up `index.ts` and `RunContext` for more clear processing flow, especially related to the cleaning of caches before persisting.
* There was a small bug caused from cleaning the cache
2. Clean up some logging

actions-dependencies-updater - fix: bugs, more cleanup

---

.changeset/short-apples-visit.md
.github/workflows/pull-request-main.yml
apps/actions-dependencies-updater/package.json
apps/actions-dependencies-updater/project.json
apps/actions-dependencies-updater/src/__tests__/actions/both-yml-yaml/action.yaml
apps/actions-dependencies-updater/src/__tests__/actions/both-yml-yaml/action.yml
apps/actions-dependencies-updater/src/__tests__/actions/single-yaml/action.yaml
apps/actions-dependencies-updater/src/__tests__/actions/single-yml/action.yml
apps/actions-dependencies-updater/src/git-cli.mts
apps/actions-dependencies-updater/src/utils.mts
apps/actions-dependencies-updater/src/utils.test.ts
pnpm-lock.yaml

Adds some basic unit testing structure, and tests to ADU.

chore: add some unit tests, tests in CI

---

.changeset/honest-melons-relate.md
actions/gha-workflow-validator/dist/index.js
actions/gha-workflow-validator/src/run.ts

Following up #422, adding a link to the summary in the output.

feat: include summary link in output

---

.changeset/strong-timers-try.md
.changeset/tender-avocados-marry.md
actions/gha-workflow-validator/action.yml
actions/gha-workflow-validator/dist/index.js
actions/gha-workflow-validator/src/__tests__/__snapshots__/utils.test.ts.snap
actions/gha-workflow-validator/src/__tests__/utils.test.ts
actions/gha-workflow-validator/src/run.ts
actions/gha-workflow-validator/src/utils.ts

* Allow file filtering to include any action definitions in repository - this will be good for this repository and all the composite actions
* Ignore commented lines in workflows or action definitions

feat: gha-workflow-validator better filtering

---

.changeset/lucky-icons-call.md
actions/setup-golang/action.yml

This adds new inputs to the `setup-golang` action.

update setup-golang action inputs

---

.changeset/flat-numbers-look.md
actions/policy-bot-config-validator/README.md
actions/policy-bot-config-validator/action.yml
actions/policy-bot-config-validator/package.json
actions/policy-bot-config-validator/project.json

Adding a reusable action which will validate `policy-bot` policy files.
Tested here: https://github.com/smartcontractkit/releng-test/actions/runs/9697793438/job/26762781365?pr=36
---
RE-2649

feat: policy bot config validator

---

.changeset/little-rockets-build.md
apps/go-mod-validator/src/deps.ts
apps/go-mod-validator/src/go-mod-validator.ts
apps/go-mod-validator/src/index.ts
apps/go-mod-validator/test/deps.test.ts
apps/go-mod-validator/test/e2e.test.ts

- **Remove useless main func**
- **Use annotation API**

RE 2843 annotation api

---

.changeset/mighty-deers-divide.md
apps/go-mod-validator/dist/index.js
apps/go-mod-validator/src/deps.ts
apps/go-mod-validator/src/github.ts

- **Add debugging statements**
- **px build**
- **add changeset**

fix: go-mod-validator

---

actions/setup-crib-environment/CHANGELOG.md
actions/setup-crib-environment/README.md
actions/setup-crib-environment/action.yml
actions/setup-crib-environment/package.json
actions/setup-crib-environment/project.json
actions/setup-gap/CHANGELOG.md
actions/setup-gap/action.yml
apps/go-mod-validator/CHANGELOG.md
apps/go-mod-validator/dist/index.js
apps/go-mod-validator/package.json
apps/go-mod-validator/src/deps.ts
apps/go-mod-validator/src/github.ts

Adding a GitHub Action for deploying a CRIB environment.
We would like to lunch it from PR flow and spin up an environment on demand.

Adding a GitHub Action for deploying a CRIB environment

---

actions/setup-gap/CHANGELOG.md
actions/setup-gap/action.yml
actions/setup-gap/package.json
apps/go-mod-validator/CHANGELOG.md
apps/go-mod-validator/dist/index.js
apps/go-mod-validator/package.json
apps/go-mod-validator/src/deps.ts
apps/go-mod-validator/src/github.ts

Reverting some changes introduced accidentally in https://github.com/smartcontractkit/.github/pull/535

Reverting changes introduced in the PR 535

---

README.md

I didn't know how to release and forgot and how changeset works, so I figured out that would be nice to have short instructions here.
Do we have a general doc about changeset I could refer here?

Add instructions about how to release actions

---

.changeset/rude-taxis-dream.md
actions/setup-crib-environment/action.yml
pnpm-lock.yaml

CRIB-269 fix setup-crib-env

---

.changeset/empty-seas-smoke.md
actions/crib-deploy-environment/action.yml

Make slack alerts configurable

---

.changeset/clean-coins-fix.md
actions/crib-deploy-environment/action.yml

🤦 Now I tested it properly here: https://github.com/smartcontractkit/crib/actions/runs/10630519054/job/29469546325?pr=130

Fix ttl label, add overwrite flag

---

.changeset/stupid-trains-thank.md
actions/gha-workflow-validator/dist/index.js
actions/gha-workflow-validator/src/__tests__/__snapshots__/output.test.ts.snap
actions/gha-workflow-validator/src/__tests__/actions-runner-validation.test.ts
actions/gha-workflow-validator/src/strings.ts
actions/gha-workflow-validator/src/validations/actions-runner-validations.ts
actions/gha-workflow-validator/src/validations/validation-check.ts

- More actionable error messages for specific actions runner failures.
--- 

feat: better actions runner error messages

---

.changeset/tasty-apricots-shake.md
actions/llm-action-error-reporter/action.yml

Fix bugs where Github output is not read properly which causes downstream errors

action error reporter 0.2.0 : Fix bugs where Github output is not read properly

---

.changeset/rare-peas-wonder.md
actions/validate-solidity-artifacts/action.yaml

Make `slither_reports_path` and `uml_diagrams_path` inputs optional

[TT-1759]  validate-solidity-artifacts optional fields

---

.changeset/calm-timers-sleep.md
actions/gha-workflow-validator/dist/index.js
actions/gha-workflow-validator/src/validations/action-reference-validations.ts
actions/gha-workflow-validator/src/validations/actions-runner-validations.ts
actions/gha-workflow-validator/src/validations/ignores-comment-validation.ts

- Found an error with my previous fix of skipping validation of workflow references. Going to disable all validations for *workflow* references
- Fix incorrect debug logging
---

fix: logging, workflow reference validation

---

.github/workflows/run-e2e-tests.yml
CODEOWNERS

1. Fixes changes introduced by https://github.com/smartcontractkit/.github/pull/636/files
2. Dynamically sets test envs if provided in `tests.test_env_vars`

Set dynamic env vars for test

---

.changeset/odd-kids-behave.md
actions/ci-sonarqube-go/README.md
actions/ci-sonarqube-go/action.yml
actions/ci-sonarqube-ts/README.md
actions/ci-sonarqube-ts/action.yml

Update SonarQube action requirements: the lint and tests workflow names are required.

Update SonarQube action requirements

---

.github/workflows/run-e2e-tests.yml

Adds input to enable/disable GAP

---

README.md
actions/update-actions/README.md

- Update main `README.md` to be more concise
- Move in-depth update explanation to `update-actions` README

docs: upgrade readme

---

.github/workflows/run-e2e-tests.yml

[TT-1806] add support for team input and CHAINLINK_USER_TEAM

---

.changeset/lazy-peas-bathe.md
actions/crib-deploy-environment/action.yml

see changeset entry for the details

Lock crib repo version

---

.changeset/few-flowers-help.md
actions/crib-deploy-environment/action.yml

Add product-dir option to enable multiple product directories.

Add product-dir option

---

.changeset/twenty-roses-destroy.md
actions/crib-deploy-environment/action.yml

Make local proxy port configurable via input

---

.changeset/slimy-ants-search.md

See title. 
I forgot to add it in my previous PR: https://github.com/smartcontractkit/.github/pull/775

Adding the local dynamic proxy configuration

---

.changeset/eighty-cooks-occur.md
actions/crib-deploy-environment/action.yml

See title.
See: 
https://github.com/smartcontractkit/.github/pull/787
https://github.com/smartcontractkit/.github/pull/775

Bumping the setup-gap GHA version

---

.changeset/long-mayflies-jog.md
actions/policy-bot-config-validator/README.md
actions/policy-bot-config-validator/action.yml

This change will generate a new major version, as new required inputs were added and a previously required input was removed.

upgraded policy-bot-config-validator to use GAP v2

---

.changeset/dry-carpets-ring.md
actions/setup-gap/action.yml

See title. 
Avoid confusion related to the API gateway that's not being used anymore.

Improve the role input parameter description

---

.changeset/breezy-forks-develop.md
actions/ctf-run-tests/action.yml

See title. 
Use the latest version.

Bump the ctf-setup-run-tests-environment version in the ctf-run-tests GitHub Action

---

.github/workflows/run-e2e-tests.yml

... in reusable e2e workflow, otherwise we just lose them.

[TT-1969] add smoke/capabilitites/logs folder to artifacts location 

---

.changeset/dry-carrots-approve.md
actions/ctf-setup-run-tests-environment/action.yml

TT-1987 ctf-setup-run-tests-environment

---

.changeset/five-months-own.md
actions/ctf-run-tests/action.yml

Update ctf-setup-run-tests-environment version.

TT-1987 ctf-run-tests

---

.github/workflows/run-e2e-tests.yml
.github/workflows/run-integration-tests.yml

Update the ctf-run-tests version.

TT-1982 run-e2e-tests run-integration-tests

---

.changeset/fluffy-rabbits-protect.md
actions/setup-postgres/.env
actions/setup-postgres/README.md
actions/setup-postgres/action.yml
actions/setup-postgres/bin/pg_dump
actions/setup-postgres/docker-compose.yml
actions/setup-postgres/package.json
actions/setup-postgres/project.json
actions/setup-postgres/wait-for-healthy-postgres.sh

Based off of: https://github.com/smartcontractkit/chainlink/tree/develop/.github/actions/setup-postgres
https://github.com/smartcontractkit/chainlink/pull/16309

feat: setup-postgres resuable action

---

.changeset/large-ligers-agree.md
actions/beholder-pulumi-deploy-schema/action.yml

Minor change: update ECR image to refer to the last one

[INFOPLAT-1856] Update ECR image name

---

actions/build-push-docker/README.md

docs: fix hyperlink build-push-docker readme

---

.changeset/chilly-plants-try.md
actions/crib-deploy-environment/action.yml
pnpm-lock.yaml

- create `ns-name-override` input
- do not error out if ns exists
- override labels

feat: update crib deploy env - ns override

---

.changeset/kind-pets-cover.md
actions/branch-names/LICENSE
actions/branch-names/README.md
actions/branch-names/action.yml
actions/branch-names/package.json
actions/branch-names/project.json
pnpm-lock.yaml

Add copy of the defunct [tj-actions/branch-names](https://github.com/tj-actions/branch-names).

feat: branch names

---

actions/ctf-build-image/action.yml

Requires:
- https://github.com/smartcontractkit/chainlink/pull/16861
Supports:
- https://github.com/smartcontractkit/chainlink-starknet/pull/599

actions/ctf-build-image: install cosmos & starknet via docker build-args

---

.changeset/late-garlics-chew.md

chore: add changeset for ctf-build-image

---

.changeset/gorgeous-olives-search.md
actions/ctf-run-tests/action.yml

Part 3 of this PR: https://github.com/smartcontractkit/.github/pull/720
Adding the new G++ setup to the run ctf tests action

Adding g++ to run on ctf run tests

---

.github/workflows/solidity-review-artifacts.yml

Upgrade `solidity-review-artifacts` reusable workflow to use pnpm 10.

fix: pnpm10 solidity-review-artifacts

---

actions/signed-commits/README.md

- I wanted to add some notes about the goosechase I just went on so hopefully no one has to do it again.

docs: signed-commits notes on tagging

---

.changeset/fluffy-dogs-do.md
actions/setup-postgres/action.yml
actions/setup-postgres/docker-compose.tmpfs.yml

- Add new `tmpfs` input to `setup-postgres` which creates a ram disk at the postgres database path.

feat: setup-postgres tmpfs

---

.github/workflows/run-e2e-tests.yml

Fix prettier linting errors on `main`
https://github.com/smartcontractkit/.github/actions/runs/15074533264/job/42378773172?pr=1038#step:3:173

fix: run-e2e-tests linting

---

.changeset/fifty-apples-press.md
actions/gha-workflow-validator/dist/index.js
actions/gha-workflow-validator/src/validations/action-reference-validations.ts

- Adds `github` as trusted owner, so we don't need to pin `github/*` actions.

chore: add github as trusted actions owner

---

.github/workflows/reusable-stale-prs-issues.yml

Creates a thin wrapper as a reusable workflow for the action: https://github.com/actions/stale

Create reusable workflow for actions/stale

---

.changeset/empty-mice-melt.md

Adding changeset because forgot in #1082 .
---
DX-1141

fix: add ctf-build-image changeset

---

.changeset/cool-months-peel.md
.changeset/fifty-eagles-confess.md
actions/oci-image-bump-receiver/README.md
actions/oci-image-bump-receiver/action.yml
actions/oci-image-bump-receiver/package.json
actions/oci-image-bump-receiver/project.json
actions/oci-image-bump-receiver/scripts/oci-image-bump-receiver.sh
actions/oci-image-bump-receiver/test.config.yaml
actions/oci-image-bump-sender/README.md
actions/oci-image-bump-sender/action.yml
actions/oci-image-bump-sender/package.json
actions/oci-image-bump-sender/project.json

- **Create oci-image-bump-receiver composite action**
- **Create oci-image-bump-sender composite action**

Create composite actions for OCI image bumping

---

.github/CODEOWNERS
.github/workflows/reusable-docker-build-publish.yml

Needs https://github.com/smartcontractkit/.github/pull/1173 merged/released.

Support manifest annotations on reusable workflow

---

.github/workflows/reusable-docker-build-publish.yml

Needs https://github.com/smartcontractkit/.github/pull/1177 merged/released.

Bump manifest action with fix for annotations

---

.changeset/wild-eggs-search.md
actions/devenv-k8s-purge-ns/action.yml
actions/devenv-k8s-setup-ns/action.yml

Refactored actions to evaluate gh expression in the env section and not in the shell script directly
It fixes issues flagged in [my previous PR](https://github.com/smartcontractkit/.github/pull/1180/commits/eae32a3f9c144346665aa28129eca39cc6356146)

Fixed code injections issues

---

.changeset/purple-books-peel.md
actions/pr-quality-check/main.py

Fixing indentation bug that was avoiding some rules to be checked + Invalidate cache if version changes

Fix/PR Quality Check Indentation Bug

---

.changeset/gold-days-sing.md
actions/codeowners-review-analysis/dist/index.js
actions/codeowners-review-analysis/scripts/payload.json
actions/codeowners-review-analysis/scripts/test.sh
actions/codeowners-review-analysis/src/review-status.ts
actions/codeowners-review-analysis/src/run-inputs.ts
actions/codeowners-review-analysis/src/strings.ts

- Fixes comment/summary formatting in a few locations
- Adds more event triggers support, as long as the PR number can be determined
Addressing formatting feedback from Seb, and adding support for `issue_comment` trigger (https://github.com/smartcontractkit/chainlink/pull/19559)
---
DX-1787

fix: cora formatting, triggers

---

actions/codeowners-review-analysis/README.md

- Add notes on workflow triggers
- Update example workflow
---
DX-1787

docs: cora readme update

---

.github/workflows/run-e2e-tests.yml

* Setup `gotestsum` before `ctf-run-tests`
* Setup auto-quarantining for `k8s-runner-tests` and `docker-tests`
https://github.com/smartcontractkit/chainlink/pull/19644
--
DX-1685

feat: run-e2e-tests branch-out

---

.changeset/forty-pumpkins-sleep.md
.github/workflows/reusable-docker-build-publish.yml
actions/build-push-docker/scripts/dockerfile_ecr_parse.sh

Fixes the error:
> Warning: Dockerfile not found at: ./v2/index-page/./v2/index-page/Dockerfile

Fix path to Dockerfile with context
